#ifndef EDITFLIGHTDIALOG_H
#define EDITFLIGHTDIALOG_H

#include <QDialog>   // Essential: Base class for dialogs
#include <QMap>    // To pass flight data in and out
#include <QDate>   // Needed for QDateEdit
#include <QTime>   // Needed for QTimeEdit

namespace Ui {
class EditFlightDialog; // Forward declaration for the generated UI class
}

class EditFlightDialog : public QDialog // Inherit from QDialog
{
    Q_OBJECT // Required for Qt's meta-object system (signals/slots)

public:
    // Default constructor: used when the dialog is created without initial data
    explicit EditFlightDialog(QWidget *parent = nullptr);

    // Overloaded constructor: used when the dialog is created with existing flight data
    explicit EditFlightDialog(const QMap<QString, QString>& flightData, QWidget *parent = nullptr);

    // Destructor: cleans up resources
    ~EditFlightDialog();

    // Public method to retrieve the flight data entered/edited by the user
    QMap<QString, QString> getFlightData();

    // Public method to pre-fill the dialog's fields with existing flight data
    void setFlightData(const QMap<QString, QString>& flightData);

private:
    Ui::EditFlightDialog *ui; // Pointer to the UI object generated by uic
};

#endif // EDITFLIGHTDIALOG_H
