#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QWidget> // MainWindow is based on QWidget (as per your UI file)
// Note: If you later change MainWindow to inherit from QMainWindow in your .ui,
// you'd change this to #include <QMainWindow>

#include "adminloginwindow.h" // Already included
#include "dashboard.h"        // ADDED: Include the Dashboard header

// Forward declarations to avoid circular includes and compile errors.
class SearchTicketWindow;
class Passenger_BookTicket;
class FlightScheduleWindow;
class FlightSearchWindow;
// class AdminLoginWindow; // Already included with header
// class Dashboard; // No longer needed as dashboard.h is included directly

namespace Ui {
class MainWindow; // Forward declaration for the UI class generated by uic
}

class MainWindow : public QWidget // Or QMainWindow if you change your .ui base class
{
    Q_OBJECT // Required for signals and slots to work

public:
    // Constructor: Takes an optional parent widget.
    explicit MainWindow(QWidget *parent = nullptr);
    // Destructor: Cleans up dynamically allocated resources (like 'ui' and child windows).
    ~MainWindow();

private slots:
    // Slot connected to the 'searchTicketButton' in your UI
    void on_searchTicketButton_clicked();

    // Add declarations for slots for your other buttons here:
    void on_passengerBookTicketButton_clicked();
    void on_flightScheduleButton_clicked();
    void on_flightSearchButton_clicked();
    void on_pushButton_8_clicked(); // Admin Login button
    void on_pushButton_9_clicked(); // Flight Manager Login button

private:
    Ui::MainWindow *ui; // Pointer to the UI object generated by uic

    // Pointers to other windows that MainWindow manages.
    // They are initialized to nullptr and created/deleted by MainWindow.
    SearchTicketWindow *searchTicketWindow;
    Passenger_BookTicket *passengerBookTicketWindow;
    FlightScheduleWindow *flightScheduleWindow;
    FlightSearchWindow *flightSearchWindow;
    AdminLoginWindow *adminLoginWindow;
    Dashboard *dashboardWin; // ADDED: Pointer to your Dashboard instance

    // Helper function to set up common styles for buttons
    void setupButtonStyles();
};

#endif // MAINWINDOW_H
