#ifndef MANAGEBOOKINGSVIEW_H
#define MANAGEBOOKINGSVIEW_H

#include <QWidget> // Base class for custom UI views
#include "bookticketdialog.h" // <<< ENSURE THIS LINE IS PRESENT

// Forward declaration of the Ui namespace
namespace Ui {
class ManageBookingsView;
}

class ManageBookingsView : public QWidget // Inherit from QWidget
{
    Q_OBJECT // Required for Qt's meta-object system (signals/slots)

public:
    explicit ManageBookingsView(QWidget *parent = nullptr);
    void loadBookings(); // Loads data into the table widget
    ~ManageBookingsView();

private slots:
    // Slot for the "Book New Ticket" button
    void on_bookTicketButton_clicked();
    // Slots for future "Confirm Ticket" and "Cancel Ticket" functionality
    void on_confirmTicketButton_clicked();
    void on_cancelTicketButton_clicked();

private:
    Ui::ManageBookingsView *ui; // Pointer to the UI object generated by uic

    void writeBookingsToCsv(const QString &filePath); // Helper to write data back to CSV (for future use)
    void applyTableStyling(); // Applies CSS-like styling to the table
};

#endif // MANAGEBOOKINGSVIEW_H
